### PR TITLE
updated the flow iconand cleaned up the provider flow state

### PR DESCRIPTION
**Pull request by xavluiz**
https://www.loom.com/share/bfe5bea262ca4267828eb21e183db0ea

### CODE REVIEW

**Comment by mmclead** [comment]
does this also update the emoji that is set in the slack status?

**Comment by xavluiz** [comment]
> does this also update the emoji that is set in the slack status?

Yes, this sets the icon next to the "Flow Mode" tree item to that blue dot icon

**Comment by mmclead** [comment]
> > does this also update the emoji that is set in the slack status?
> 
> Yes, this sets the icon next to the "Flow Mode" tree item to that blue dot icon

Ah, but we also want it to set the icon inside of slack itself to the :large_purple_circle: 
Right now it's the text bubble.

**Comment by xavluiz** [comment]
> > > does this also update the emoji that is set in the slack status?
> > 
> > 
> > Yes, this sets the icon next to the "Flow Mode" tree item to that blue dot icon
> 
> Ah, but we also want it to set the icon inside of slack itself to the :large_purple_circle:
> Right now it's the text bubble.

Oh, i see. So when a user updates enables flow we'll set the emoji to that. I get it. cool, thanks. Will update

**Review by brettmstevens7 — APPROVED** [review]

**Pull request merged**
